spring:
  datasource:
    url: jdbc:h2:mem:dbtest;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
beetlsql: sqlManager
beetlsql.sqlManager.ds: dataSource
beetlsql.sqlManager.basePackage: com.github.daihy8759
beetlsql.sqlManager.daoSuffix: Mapper
beetlsql.sqlManager.dbStyle: org.beetl.sql.core.db.H2Style